CREATE TABLE IF NOT EXISTS aluno (
	id SERIAL PRIMARY KEY,
	primeiro_nome VARCHAR(255) NOT NULL,
	ultimo_nome VARCHAR(255) NOT NULL,
	data_nascimento DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS categoria (
	id 	SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS curso (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL UNIQUE,
	catetgoria_id INTEGER NOT NULL REFERENCES categoria(id)
);

CREATE TABLE IF NOT EXISTS aluno_curso (
	aluno_id INTEGER NOT NULL REFERENCES aluno(id),
	curso_id INTEGER NOT NULL REFERENCES curso(id),
	PRIMARY KEY (aluno_id, curso_id)
);